### PR TITLE
Check the output

### PR DESCRIPTION
**Pull request by szepeviktor**
thus the Composer configuration

### CODE REVIEW

**Comment by szepeviktor** [comment]
@LeoColomb PR-s don't have access to `GITHUB TOKEN` :(

**Comment by LeoColomb** [comment]
Interesting change, but I'm not sure this is worth running each build, as it follows a template (which might be the one to validate).

> PR-s don't have access to `GITHUB TOKEN` :(

This is normal, this script is only run on a cron schedule basis. It should not run at every commit.

Note that I'm slowly moving the script to https://github.com/composer-wordpress/build, I plan to rewrite the build for much more granularity.

**Comment by szepeviktor** [comment]
> Interesting change, but I'm not sure this is worth running each build, as it follows a template (which might be the one to validate).

If I would be in your place I wouldn't publish `composer.json` without validation.

**Comment by LeoColomb** [comment]
I'm closing if favor of https://github.com/composer-wordpress/build/issues/1

**Pull request closed without merging**
